"""Utility to parse the generated content from Gemini into structured training examples."""

import re
import json
from typing import Dict, Any, List, Optional

def parse_generated_content(content: str) -> Dict[str, Any]:
    """Parse the content generated by Gemini into a structured training example.
    
    The expected format includes:
    1. A user query
    2. An assistant response that calls a tool
    3. A tool response
    4. A final assistant response
    
    Returns:
        A dictionary with the parsed conversation elements
    """
    parts = re.split(r'\n(?:User|Assistant|Tool|System):', content)
    
    conversation = []
    current_role = None
    
    for i, part in enumerate(parts):
        if i == 0 and not part.strip():
            continue
            
        role_match = re.search(r'(User|Assistant|Tool|System):', 
                              content.split(part)[0].split('\n')[-1] if i > 0 else '')
        
        if role_match:
            current_role = role_match.group(1).lower()
            
            cleaned_content = part.strip()
            
            if current_role == 'assistant':
                tool_call_match = re.search(r'```json\s*(.*?)\s*```', cleaned_content, re.DOTALL)
                
                if tool_call_match:
                    try:
                        tool_call_json = json.loads(tool_call_match.group(1))
                        conversation.append({
                            "role": "assistant",
                            "content": None,
                            "tool_calls": [
                                {
                                    "id": f"call_{len(conversation)}",
                                    "type": "function",
                                    "function": {
                                        "name": tool_call_json.get("name", ""),
                                        "arguments": json.dumps(tool_call_json.get("arguments", {}))
                                    }
                                }
                            ]
                        })
                    except json.JSONDecodeError:
                        conversation.append({
                            "role": "assistant",
                            "content": cleaned_content
                        })
                else:
                    conversation.append({
                        "role": "assistant",
                        "content": cleaned_content
                    })
            elif current_role == 'tool':
                tool_name_match = re.search(r'Tool: (.*?) Result:', cleaned_content)
                tool_name = tool_name_match.group(1) if tool_name_match else ""
                
                result_content = re.sub(r'^.*?Result:', '', cleaned_content, flags=re.DOTALL).strip()
                
                conversation.append({
                    "role": "tool",
                    "tool_call_id": f"call_{len(conversation)-1}",
                    "name": tool_name,
                    "content": result_content
                })
            else:
                conversation.append({
                    "role": current_role,
                    "content": cleaned_content
                })
    
    return {
        "messages": conversation,
        "tools": [], # This will be filled in by the validation step
        "functions": [] # Legacy format, kept for compatibility
    }
